-- MySQL Script generated by MySQL Workbench
-- Fri Sep 20 00:37:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FI-AR
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FI-AR
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FI-AR` DEFAULT CHARACTER SET utf8 ;
USE `FI-AR` ;

-- -----------------------------------------------------
-- Table `FI-AR`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FI-AR`.`Students` (
  `Student_Name` VARCHAR(45) NOT NULL,
  `MarticNo` VARCHAR(9) NOT NULL,
  `Phot_URL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MarticNo`),
  CONSTRAINT `MarticNo`
    FOREIGN KEY (`MarticNo`)
    REFERENCES `FI-AR`.`Student Index` (`MarticNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FI-AR`.`Student Index`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FI-AR`.`Student Index` (
  `MarticNo` VARCHAR(9) NOT NULL,
  `IndexNo` INT NOT NULL,
  PRIMARY KEY (`MarticNo`, `IndexNo`),
  INDEX `IndexNo` (`IndexNo` ASC) VISIBLE,
  CONSTRAINT `IndexNo`
    FOREIGN KEY (`IndexNo`)
    REFERENCES `FI-AR`.`Index` (`IndexNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MatricNo`
    FOREIGN KEY (`MarticNo`)
    REFERENCES `FI-AR`.`Students` (`MarticNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FI-AR`.`Index`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FI-AR`.`Index` (
  `Course_Code` VARCHAR(6) NOT NULL,
  `IndexNo` INT NOT NULL,
  `Lab_Venue` VARCHAR(45) NOT NULL,
  `Start_Time` TIME NULL,
  `End_Time` TIME NULL,
  PRIMARY KEY (`IndexNo`),
  INDEX `Course_Code_idx` (`Course_Code` ASC) INVISIBLE,
  CONSTRAINT `Course_Code`
    FOREIGN KEY (`Course_Code`)
    REFERENCES `FI-AR`.`Course` (`Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IndexNo`
    FOREIGN KEY (`IndexNo`)
    REFERENCES `FI-AR`.`Student Index` (`IndexNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FI-AR`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FI-AR`.`Course` (
  `Code` VARCHAR(6) NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Code`),
  CONSTRAINT `Code`
    FOREIGN KEY (`Code`)
    REFERENCES `FI-AR`.`Index` (`Course_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
